# Compilazione
FROM golang:1.25-alpine AS builder

WORKDIR /app

# Installa l'intero set di strumenti di compilazione (gcc, musl-dev, make, ecc.)
RUN apk add --no-cache git build-base

# Copia i file delle dipendenze
COPY go.mod go.sum ./
RUN go mod download

# Copia il codice sorgente
COPY . .

# Compila l'eseguibile forzando l'uso di CGO
ENV CGO_ENABLED=1
RUN go build -o webapi ./cmd/webapi

# Step 2: Runtime
FROM alpine:latest

WORKDIR /root/

# Copia l'eseguibile dallo step precedente
COPY --from=builder /app/webapi .

# Espone la porta del backend
EXPOSE 3000

# Avvia l'app
CMD ["./webapi"]